### ISSUE TITLE
Build is failing instantly after adding composer plugin

### ISSUE THREAD

**Issue by outlying** [gojuno/composer#106]
Composer: `0.3.0`
Android Gradle plugin: `3.0.0-rc1`

After adding plugin `apply plugin: 'composer'` I get the following result

    FAILURE: Build failed with an exception.
    
    * What went wrong:
    A problem occurred configuring project ':app'.
    > Failed to notify project evaluation listener.
       > com.android.build.gradle.api.ApplicationVariant.getOutputs()Ljava/util/List;
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 0s

This part of the stack trace might be useful

    Caused by: java.lang.NoSuchMethodError: com.android.build.gradle.api.ApplicationVariant.getOutputs()Ljava/util/List;
        at com.trevjonez.composer.ComposerPlugin.apkForVariant(ComposerPlugin.kt:134)
        at com.trevjonez.composer.ComposerPlugin.getApk(ComposerPlugin.kt:109)
        at com.trevjonez.composer.ComposerPlugin.access$getApk(ComposerPlugin.kt:28)
        at com.trevjonez.composer.ComposerPlugin$observeVariants$1.execute(ComposerPlugin.kt:67)
        at com.trevjonez.composer.ComposerPlugin$observeVariants$1.execute(ComposerPlugin.kt:28)

I will provide more information if needed

**Comment by plastiv** [comment]
@outlying Wrong project? Issue seems to be with composer gradle plugin and not composer binary https://github.com/trevjonez/composer-gradle-plugin

**Comment by outlying** [comment]
Right my bad, I forget that you are not supporting Gradle plugin
