### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by JankoCvirn** [gojuno/composer#153]
When running 
java -jar composer-0.3.3.jar --apk app-internal-debug.apk --test-apk app-internal-debug-androidTest.apk

there is an exception:
Exception in thread "main" java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.collections.ArraysKt___ArraysKt.sortedArray, parameter $receiver
	at kotlin.collections.ArraysKt___ArraysKt.sortedArray(_Arrays.kt)
	at com.gojuno.commander.android.AdbKt$buildTools$2.invoke(Adb.kt:19)
	at com.gojuno.commander.android.AdbKt$buildTools$2.invoke(Adb.kt)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at com.gojuno.commander.android.AdbKt.getBuildTools(Adb.kt)
	at com.gojuno.commander.android.AdbKt.access$getBuildTools$p(Adb.kt:1)
	at com.gojuno.commander.android.AdbKt$aapt$2.invoke(Adb.kt:23)
	at com.gojuno.commander.android.AdbKt$aapt$2.invoke(Adb.kt)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at com.gojuno.commander.android.AdbKt.getAapt(Adb.kt)
	at com.gojuno.composer.ApkKt.parseTestPackage(Apk.kt:18)
	at com.gojuno.composer.MainKt.main(Main.kt:40)

I can run the tests using adb .
Apk's are placed in the same folder as the composer-0.3.3.jar.

Which parameter is missing?

**Comment by JankoCvirn** [comment]
Didnt have Android SDK in my path.
