### ISSUE TITLE
NumberFormatException while running tests with composer

### ISSUE THREAD

**Issue by ripunjayasaran** [gojuno/composer#79]
When trying to run the tests while using the composer jar file (v 0.2.2), i get a NumberFormatException. The issue is being caused from the Intrumentation.kt class at line 62 when trying to convert the string to integer: 
Error trying to convert "numtests" into integer >
 numTests = str.parseInstrumentationStatusValue("numtests").toInt()

https://github.com/gojuno/composer/blob/master/composer/src/main/kotlin/com/gojuno/composer/Instrumentation.kt

See below screenshot for more details. The command used to run the tests can be seen in the screenshot. Also, our project is using RxJava 1.x if that helps. If you would like a log file of the error, then please let me know.
![screen shot 2017-06-28 at 6 03 49 pm](https://user-images.githubusercontent.com/15218475/27668252-f30cfbee-5c4d-11e7-9812-668a929f07a1.png)

**Comment by artem-zinnatullin** [comment]
Interesting, can you please attach instrumentation.output file from test run? By default Composer stores such files in `composer-output/logs/deviceId/instrumentation.output`?

Also, version of Android on device and host OS would help, thanks!

**Comment by ripunjayasaran** [comment]
@artem-zinnatullin : Here is the output of the instrumentation.output file:
android.util.AndroidException: INSTRUMENTATION_FAILED: com.weighwatchers.mobile.tests/com.weightwatchers.mobile.rxespresso.RxAndroidJUnitRunner
	at com.android.commands.am.Am.runInstrument(Am.java:918)
	at com.android.commands.am.Am.onRun(Am.java:404)INSTRUMENTATION_STATUS: id=ActivityManagerService

	at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
	at com.android.commands.am.Am.main(Am.java:125)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:301)
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.weighwatchers.mobile.tests/com.weightwatchers.mobile.rxespresso.RxAndroidJUnitRunner}
INSTRUMENTATION_STATUS_CODE: -1

This is the entire output that i see when i try to run tests with composer-0.2.3.jar : 

$java -jar composer-0.2.3.jar --apk app/build/outputs/apk/app-dev-debug.apk --test-apk app/build/outputs/apk/app-dev-debug-androidTest.apk --test-package com.weighwatchers.mobile.tests --test-runner com.weightwatchers.mobile.rxespresso.RxAndroidJUnitRunner
[Thu Jun 29 12:50:28 EDT 2017]: 1 connected adb device(s): [AdbDevice(id=074df8d5, online=true)]
[Thu Jun 29 12:50:28 EDT 2017]: [074df8d5] Installing apk... pathToApk = app/build/outputs/apk/app-dev-debug.apk
[Thu Jun 29 12:50:43 EDT 2017]: [074df8d5] Successfully installed apk in 15 seconds, pathToApk = app/build/outputs/apk/app-dev-debug.apk
[Thu Jun 29 12:50:43 EDT 2017]: [074df8d5] Installing apk... pathToApk = app/build/outputs/apk/app-dev-debug-androidTest.apk
[Thu Jun 29 12:50:47 EDT 2017]: [074df8d5] Successfully installed apk in 4 seconds, pathToApk = app/build/outputs/apk/app-dev-debug-androidTest.apk
[Thu Jun 29 12:50:47 EDT 2017]: [074df8d5] Starting tests...
[Thu Jun 29 12:50:48 EDT 2017]: [074df8d5] Error during tests run: java.lang.IllegalStateException: Process [/Users/ripunjaya.saran/Library/Android/sdk/platform-tools/adb, -s, 074df8d5, shell, am instrument -w -r com.weighwatchers.mobile.tests/com.weightwatchers.mobile.rxespresso.RxAndroidJUnitRunner] exited with non-zero code 1 android.util.AndroidException: INSTRUMENTATION_FAILED: com.weighwatchers.mobile.tests/com.weightwatchers.mobile.rxespresso.RxAndroidJUnitRunner
	at com.android.commands.am.Am.runInstrument(Am.java:918)
	at com.android.commands.am.Am.onRun(Am.java:404)INSTRUMENTATION_STATUS: id=ActivityManagerService

	at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
	at com.android.commands.am.Am.main(Am.java:125)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:301)
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.weighwatchers.mobile.tests/com.weightwatchers.mobile.rxespresso.RxAndroidJUnitRunner}
INSTRUMENTATION_STATUS_CODE: -1

Exception in thread "main" java.lang.IllegalStateException: Process [/Users/ripunjaya.saran/Library/Android/sdk/platform-tools/adb, -s, 074df8d5, shell, am instrument -w -r com.weighwatchers.mobile.tests/com.weightwatchers.mobile.rxespresso.RxAndroidJUnitRunner] exited with non-zero code 1 android.util.AndroidException: INSTRUMENTATION_FAILED: com.weighwatchers.mobile.tests/com.weightwatchers.mobile.rxespresso.RxAndroidJUnitRunner
	at com.android.commands.am.Am.runInstrument(Am.java:918)
	at com.android.commands.am.Am.onRun(Am.java:404)INSTRUMENTATION_STATUS: id=ActivityManagerService

	at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
	at com.android.commands.am.Am.main(Am.java:125)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:301)
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.weighwatchers.mobile.tests/com.weightwatchers.mobile.rxespresso.RxAndroidJUnitRunner}
INSTRUMENTATION_STATUS_CODE: -1

	at com.gojuno.commander.os.ProcessesKt$process$1.call(Processes.kt:97)
	at com.gojuno.commander.os.ProcessesKt$process$1.call(Processes.kt)
	at rx.internal.operators.OnSubscribeCreate.call(OnSubscribeCreate.java:72)
	at rx.internal.operators.OnSubscribeCreate.call(OnSubscribeCreate.java:32)
	at rx.Observable.unsafeSubscribe(Observable.java:10256)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ripunjayasaran** [comment]
I also ran the tests against Android 6.0.1 device and saw the same error. I am attaching the instrumentation.output and the console output again for reference here:
[instrumentation.output_android6.0.1.txt](https://github.com/gojuno/composer/files/1112913/instrumentation.output_android6.0.1.txt)
[consoleoutput_android6.0.1.txt](https://github.com/gojuno/composer/files/1112914/consoleoutput_android6.0.1.txt)

**Comment by jeslat** [comment]
Hi, I have the same problem that @ripunjayasaran. I'm trying to run my espresso tests with an Android emulator 7.0 in Mac OS Sierra and I have this error info in `instrumentation.output`:
```
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.xxx.zzz/com.xxx.zzz.test.runner.RetryAndroidJUnit4}
INSTRUMENTATION_STATUS_CODE: -1
android.util.AndroidException: INSTRUMENTATION_FAILED: com.xxx.zzz/com.xxx.zzz.test.runner.RetryAndroidJUnit4
	at com.android.commands.am.Am.runInstrument(Am.java:1093)
	at com.android.commands.am.Am.onRun(Am.java:371)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
	at com.android.commands.am.Am.main(Am.java:100)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)

```

**Comment by artem-zinnatullin** [comment]
Yup yup, we're looking into this, sorry for delay, your logs are very helpful btw!

**Comment by ripunjayasaran** [comment]
@artem-zinnatullin : any ETA on when we can expect this issue to be fixed? Thanks.

**Comment by artem-zinnatullin** [comment]
Sorry for huge delay, I was traveling. 

@ripunjayasaran and @jeslat I looked more into your logs and actually it seems like you both have app project configuration issue https://stackoverflow.com/questions/16591504/android-studio-import-existing-unit-tests-unable-to-find-instrumentation-info

So it seems that it's not related to Composer itself.

However we definitely should parse and print such errors in a more appropriate way and print something like "Please check path/instrumentation.output for more details" cc @yunikkk, @ming13

**Comment by jeslat** [comment]
Thank you for checking it, I'll review that configuration issue.

**Comment by ripunjayasaran** [comment]
@artem-zinnatullin : from what i understand you are basically referring to the approach described [here](https://stackoverflow.com/a/36597497/8268378) in the same link. However, this approach only works if you have android studio 2.2 or lower. It has been removed in android studio 2.3 . Please correct me if i am wrong.

**Comment by yunikkk** [comment]
@ripunjayasaran the error means that smth is wrong with your TestRunner and the way it is specified. It should be set in your build.gradle with 
```android {
    defaultConfig {
        testInstrumentationRunner "FULL_RUNNER_PATH"
```
and you should specify it correctly with composer, too. 

Finally, you should be able to open the generated `AndroidManifest.xml` file for your instrumentation project (under `build/intermediates/manifest/androidTest/debug/` path). There `package` should be equal to `--test-package ` and  `android:name` attr from `<instrumentation ...>` - to `--test-runner` from Composer invocation.

**Comment by yunikkk** [comment]
Also, you could always recheck that `adb` is able to run instrumentation without Composer, try
`adb shell am instrument -w TEST_PACKAGE/TEST_RUNNER`, if it works - Composer should work too.

**Comment by ripunjayasaran** [comment]
@yunikkk, @artem-zinnatullin : Thanks a lot for this information, I figured out the issue and now have Composer up and running. I was supplying the test package in which my tests are located instead of the one in the AndroidManifest file. We should perhaps add this info in the read me file as well as it could confuse others as well. 
Closing this issue.

**Comment by artem-zinnatullin** [comment]
@ripunjayasaran well it's not really related to Composer, it doesn't require you to use specific build system, etc :)
