### ISSUE TITLE
Suite::class.java.classL…getResourceAsStream(path) must not be null

### ISSUE THREAD

**Issue by Mauin** [gojuno/composer#93]
After a test run with composer is finished I see the following exception when Composer is trying to generate the HTML report. 

Composer version: Build locally against current HEAD of `master`

```
[Tue Aug 01 15:01:32 CEST 2017]: Generating HTML report...
Exception in thread "main" java.lang.IllegalStateException: Suite::class.java.classL…getResourceAsStream(path) must not be null
	at com.gojuno.composer.html.HtmlReportKt.inputStreamFromResources(HtmlReport.kt:92)
	at com.gojuno.composer.html.HtmlReportKt$writeHtmlReport$1.call(HtmlReport.kt:31)
	at com.gojuno.composer.html.HtmlReportKt$writeHtmlReport$1.call(HtmlReport.kt)
	at rx.Completable$9.call(Completable.java:495)
	at rx.Completable$9.call(Completable.java:489)
	at rx.Completable.unsafeSubscribe(Completable.java:2035)
	at rx.Completable$19.call(Completable.java:1365)
	at rx.Completable$19.call(Completable.java:1362)
	at rx.Completable.unsafeSubscribe(Completable.java:2035)
	at rx.Completable.unsafeSubscribe(Completable.java:2083)
	at rx.Completable.unsafeSubscribe(Completable.java:2067)
	at rx.Completable$32.call(Completable.java:2253)
	at rx.Completable$32.call(Completable.java:2250)
	at rx.Observable.unsafeSubscribe(Observable.java:10256)
	at rx.internal.operators.OnSubscribeDelaySubscriptionOther.call(OnSubscribeDelaySubscriptionOther.java:80)
	at rx.internal.operators.OnSubscribeDelaySubscriptionOther.call(OnSubscribeDelaySubscriptionOther.java:31)
	at rx.Observable.unsafeSubscribe(Observable.java:10256)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
	at rx.internal.operators.OperatorZip$Zip.tick(OperatorZip.java:252)
	at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onNext(OperatorZip.java:323)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.SingleLiftObservableOperator$WrapSubscriberIntoSingle.onSuccess(SingleLiftObservableOperator.java:76)
	at rx.Single$13$1$1.onSuccess(Single.java:2016)
	at rx.Completable$33$1.onCompleted(Completable.java:2287)
	at rx.Completable$11$1.onSuccess(Completable.java:614)
	at rx.internal.operators.SingleOnSubscribeMap$MapSubscriber.onSuccess(SingleOnSubscribeMap.java:74)
	at rx.internal.operators.SingleOnSubscribeMap$MapSubscriber.onSuccess(SingleOnSubscribeMap.java:74)
	at rx.internal.operators.SingleFromCallable.call(SingleFromCallable.java:48)
	at rx.internal.operators.SingleFromCallable.call(SingleFromCallable.java:29)
	at rx.Single.subscribe(Single.java:1962)
	at rx.internal.operators.SingleOnSubscribeMap.call(SingleOnSubscribeMap.java:45)
	at rx.internal.operators.SingleOnSubscribeMap.call(SingleOnSubscribeMap.java:30)
	at rx.Single.subscribe(Single.java:1962)
	at rx.internal.operators.SingleOnSubscribeMap.call(SingleOnSubscribeMap.java:45)
	at rx.internal.operators.SingleOnSubscribeMap.call(SingleOnSubscribeMap.java:30)
	at rx.Single.subscribe(Single.java:1962)
	at rx.Completable$11.call(Completable.java:619)
	at rx.Completable$11.call(Completable.java:602)
	at rx.Completable.unsafeSubscribe(Completable.java:2035)
	at rx.Completable$33.call(Completable.java:2271)
	at rx.Completable$33.call(Completable.java:2268)
	at rx.Single.subscribe(Single.java:1962)
	at rx.Single$2$1.onSuccess(Single.java:670)
	at rx.Single$2$1.onSuccess(Single.java:666)
	at rx.internal.operators.SingleOnSubscribeMap$MapSubscriber.onSuccess(SingleOnSubscribeMap.java:74)
	at rx.internal.operators.OnSubscribeSingle$1.onCompleted(OnSubscribeSingle.java:55)
	at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:80)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
	at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
	at rx.internal.operators.OperatorZip$Zip.tick(OperatorZip.java:252)
	at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onNext(OperatorZip.java:323)
	at rx.internal.operators.OperatorZip$Zip.tick(OperatorZip.java:252)
	at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onNext(OperatorZip.java:323)
	at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
	at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
	at rx.internal.operators.OperatorToObservableList$1.onCompleted(OperatorToObservableList.java:98)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:656)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:857)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onCompleted(OperatorSubscribeOn.java:89)
	at rx.internal.producers.SingleProducer.request(SingleProducer.java:75)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber$1$1.call(OperatorSubscribeOn.java:114)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by artem-zinnatullin** [comment]
Most likely you didn't build Composer properly. You need to build html report app first.

I strongly recommend to install Docker and just run `ci/build.sh` as described in ["How to build" section of README](https://github.com/gojuno/composer#how-to-build) :)

**Comment by artem-zinnatullin** [comment]
Feel free to comment if you still have the issue, happy emoji on my reply would be good if it helped with your issue!

**Comment by Mauin** [comment]
You're right, I assumed that a simple `gradle build` would be enough and skipped the "How to build" part in the `README.md`. Sorry for the noise!

**Comment by artem-zinnatullin** [comment]
Np!

Once you build it with "ci/build.sh" you can continue using Gradle as usual
unless you want to make changes in html app :)
